apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: fix-kaniko-special-casing
    build: "1"
    owner: jenkins-x
    repo: jx
  name: jenkins-x-jx-fix-kaniko-special-9l9zj-1
spec:
  params:
    - name: version
      value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: jenkins-x-jx-fix-kaniko-special-9l9zj-1
  resources:
    - name: jenkins-x-jx-fix-kaniko-special-9l9zj
      resourceRef:
        apiVersion: tekton.dev/v1alpha1
        name: jenkins-x-jx-fix-kaniko-special-9l9zj
  serviceAccount: tekton-bot
  timeout: 240h0m0s
  trigger:
    type: manual
status: {}
