apiVersion: tekton.dev/v1alpha1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    creationTimestamp: "2019-07-02T12:34:56Z"
    generation: 1
    name: abayer-js-test-repo-build-pack-8
    namespace: jx
    ownerReferences:
    - apiVersion: jenkins.io/v1
      kind: PipelineActivity
      name: abayer-js-test-repo-build-pack-8
      uid: c5e1fa64-9cc5-11e9-aa2e-42010a8a00fe
    resourceVersion: "235864"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/pipelines/abayer-js-test-repo-build-pack-8
    uid: cc57794e-9cc5-11e9-aa2e-42010a8a00fe
  spec:
    params:
    - default: 0.0.7
      description: the version number for this pipeline which is used as a tag on docker
        images and helm charts
      name: version
    - default: "8"
      description: the PipelineRun build number
      name: build_id
    resources:
    - name: abayer-js-test-repo-build-pack
      type: git
    tasks:
    - name: from-build-pack
      params:
      - name: version
        value: ${params.version}
      - name: build_id
        value: ${params.build_id}
      resources:
        inputs:
        - name: workspace
          resource: abayer-js-test-repo-build-pack
      taskRef:
        name: abayer-js-test-repo-build-pack-from-build-pack-8
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    creationTimestamp: "2019-07-02T12:34:45Z"
    generation: 1
    labels:
      branch: build-pack
      build: "8"
      owner: abayer
      repo: js-test-repo
    name: meta-abayer-js-test-repo-build-8
    namespace: jx
    ownerReferences:
      - apiVersion: jenkins.io/v1
        kind: PipelineActivity
        name: abayer-js-test-repo-build-pack-meta-8
        uid: c57379a2-9cc5-11e9-aa2e-42010a8a00fe
    resourceVersion: "235775"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/pipelines/meta-abayer-js-test-repo-build-8
    uid: c5ad1626-9cc5-11e9-aa2e-42010a8a00fe
  spec:
    resources:
      - name: meta-abayer-js-test-repo-build
        type: git
    tasks:
      - name: app-extension
        resources:
          inputs:
            - name: workspace
              resource: meta-abayer-js-test-repo-build
        taskRef:
          name: meta-abayer-js-test-repo-build-app-extension-8
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
