coverage:
  status:
    project:
      default:
        # auto will
        target: auto
        # For now, only use integration for the patch target as we aren't reporting e2e on release builds
        flags: integration
    patch:
      default:
        # For now, only use integration for the patch target as we aren't reporting e2e on release builds
        flags: integration
        target: 70%
codecov:
  ci:
    # GitHub Contexts to use to consider the CI complete. Once all contexts go green, codecov will report
    # Contexts starting with ! are excluded from consideration
    - !DCO
    - !Hound
    - !lint
    - !tide
    - integration
    - bdd
    - tekton
