metadata:
  creationTimestamp: null
  name: abayer-js-test-repo-really-long-1
  labels:
    branch: really-long
    build: "1"
    owner: abayer
    repo: js-test-repo
pipelineRef: null
pipelineRunRef: null
stages:
  - depth: 0
    name: Build-a-really-long-stage-name-please-but-not-too-long-thanks
    taskRef: abayer-js-test-repo-really-long-build-a-really-long-stage-nam-1
